#include "structs.hpp"
#include <iostream>

using namespace std;

string* initializeStory(GameState state) {
    switch (state.week) {
        case 0:
            string *dialogues = new string[200]{
                "???: Good evening.",
                "???: It's a bit late here, but I'd like to talk a little about myself.",
                "$CLEAR",
                "Fait: My name is Fait.",
                "Fait: Recently, I got into PASUM! I didn't actually expect to get in, considering my...",
                "...",
                "Fait: Ethnic...",
                "Fait: Anyhow! I'm pretty excited to get into PASUM!",
                "Fait: I'll miss my family, since I'd have to move away from S*rawak.",
                "Fait: Especially, my Ald*n and A*stralia.",
                "Fait: *Yawns*, I guess nothing else to do but to get ready now.",
                "Fait: Good Night!",
                "$CLEAR",
                "...",
                "...",
                "...",
                "...",
                "...",
                "*The plane crashes, Fait suffers a severe head injury.*",
                "$CLEAR",
                "Fait: ...",
                "$END"
            };
            return dialogues;
    }


    string *dialogues = new string[200]{
        "Kuu: Oops! It broke!",
        "Kuu: Tell me or Faith!",
    };
    return dialogues;
}

string* initializeInterlude(GameState state) {
    switch (state.week) {
        case 0:
            string *dialogues = new string[200]{
                "$CLEAR",
                "???: Follow my finger. Left, right, left, right.",
                "Fait: *Eyes trailing, but lagging behind*",
                "$CLEAR",
                "???: That's enough. So, tell me, Fait, how are you feeling so far?",
                "Fait: I'm feeling fine so far, but I feel a lot more stressed out lately",
                "???: Is it because of PASUM?",
                "Fait: I think so?",
                "???: Have you been feeling it much more intensely?",
                "Fait: I think so...?",
                "Fait: It's just that...",
                "$CLEAR",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "Fait: ...",
                "???: ..?",
                "$STREAMFAST",
                "I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE I WANNA DIE ",
                "$STREAMSLOW",
                "Fait: I was never the one in control...",
                "$END"
            };
            return dialogues;
    }


    string *dialogues = new string[200]{
        "Kuu: Oops! It broke!",
        "Kuu: Tell me or Faith!",
        "Kuu: Or... Thanks for getting scared?"
    };
    return dialogues;
}
